### ISSUE TITLE
Painful contrast

### ISSUE THREAD

**Issue by pepelsbey** [una/caniuse-component#5]
In case of Edge logo on red background contrast is very low and it’s particulary painful to look at such color combination for some reason:

![image](https://cloud.githubusercontent.com/assets/105274/18544728/b148e5ec-7b3e-11e6-8d4b-a56a5a86a4cd.png)

In case of Opera not supporting a feature it gets even worse:

![image](https://cloud.githubusercontent.com/assets/105274/18544772/dff684f8-7b3e-11e6-9311-d3e2b43e6011.png)

I took material design palette to test if less saturated color would work better and it seems so:

![image](https://cloud.githubusercontent.com/assets/105274/18544843/45a8ae48-7b3f-11e6-9150-c69a44d1374e.png)

I could send a PR, but you might want to figure out exact colors yourself. But I’ll do it if you’re fine with suggested ones.

**Comment by una** [comment]
Thanks for the issue -- I originally had lighter colors like those but ended up resaturating them because it looked more modern (but you're right -- usability over aesthetic) -- will take another look at the defaults

**Comment by pepelsbey** [comment]
I agree, full bright colors would look better. To keep them I’d look for monochome simplified white browser logos. It would be easy in case of Edge and here’s [logos collection for Opera](https://operasoftware.github.io/logo/) I made a while ago. I can see how this could be easily done for Safari and Chrome as well, but I haven’t seen any good monochome Firefox logos.

**Comment by una** [comment]
Updates in release 0.1.3 https://github.com/una/caniuse-component/tree/0.1.3
